// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mQcR2v1mqF-auaM7QHdDFQaNCo18HO4',
    appId: '1:119213200027:web:ab73b5cd3989bcf0cf6c3e',
    messagingSenderId: '119213200027',
    projectId: 'crawlerdb-320d6',
    authDomain: 'crawlerdb-320d6.firebaseapp.com',
    databaseURL: 'https://crawlerdb-320d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crawlerdb-320d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxYOSPmxFxWf--9oJ50tkVqi9vee9xRE',
    appId: '1:119213200027:android:7a903e1eabb32652cf6c3e',
    messagingSenderId: '119213200027',
    projectId: 'crawlerdb-320d6',
    databaseURL: 'https://crawlerdb-320d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crawlerdb-320d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKIVzQqSmbz3EHeulNYSu0yVkbjT3bZg',
    appId: '1:119213200027:ios:dd2b7cf595a355d5cf6c3e',
    messagingSenderId: '119213200027',
    projectId: 'crawlerdb-320d6',
    databaseURL: 'https://crawlerdb-320d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crawlerdb-320d6.appspot.com',
    iosClientId: '119213200027-quunbfs9o67rs7lsmsgjinrh532847p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKIVzQqSmbz3EHeulNYSu0yVkbjT3bZg',
    appId: '1:119213200027:ios:dd2b7cf595a355d5cf6c3e',
    messagingSenderId: '119213200027',
    projectId: 'crawlerdb-320d6',
    databaseURL: 'https://crawlerdb-320d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crawlerdb-320d6.appspot.com',
    iosClientId: '119213200027-quunbfs9o67rs7lsmsgjinrh532847p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
